// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A Genkit flow that generates personalized introductory emails to prospective clients.
 *
 * - generateIntroductoryEmail - A function that handles the email generation process.
 * - GenerateIntroductoryEmailInput - The input type for the generateIntroductoryEmail function.
 * - GenerateIntroductoryEmailOutput - The return type for the generateIntroductoryEmail function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateIntroductoryEmailInputSchema = z.object({
  linkedinProfileUrl: z
    .string()
    .describe('The URL of the LinkedIn profile of the prospective client.'),
  recentPosts: z
    .string()
    .describe('The recent posts of the prospective client.'),
  companyNews: z
    .string()
    .describe('The latest news about the prospective client’s company.'),
  tone: z
    .string()
    .default('professional, intelligent, approachable, trustworthy, credible but humble')
    .describe('The tone of the email.'),
});

export type GenerateIntroductoryEmailInput = z.infer<typeof GenerateIntroductoryEmailInputSchema>;

const GenerateIntroductoryEmailOutputSchema = z.object({
  email: z.string().describe('The generated introductory email.'),
});

export type GenerateIntroductoryEmailOutput = z.infer<typeof GenerateIntroductoryEmailOutputSchema>;

export async function generateIntroductoryEmail(input: GenerateIntroductoryEmailInput): Promise<GenerateIntroductoryEmailOutput> {
  return generateIntroductoryEmailFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateIntroductoryEmailPrompt',
  input: {schema: GenerateIntroductoryEmailInputSchema},
  output: {schema: GenerateIntroductoryEmailOutputSchema},
  prompt: `You are an AI assistant that specializes in crafting personalized introductory emails to prospective clients.

  Based on the information provided about the prospect's LinkedIn profile, recent posts, and company news, generate a compelling and personalized introductory email.
  The email should be tailored to the prospect's interests and needs, and should clearly communicate the value proposition of Alex Myers as an advisor, speaker, and consultant.

  LinkedIn Profile URL: {{{linkedinProfileUrl}}}
  Recent Posts: {{{recentPosts}}}
  Company News: {{{companyNews}}}
  Tone: {{{tone}}}

  Email: `,
});

const generateIntroductoryEmailFlow = ai.defineFlow(
  {
    name: 'generateIntroductoryEmailFlow',
    inputSchema: GenerateIntroductoryEmailInputSchema,
    outputSchema: GenerateIntroductoryEmailOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
