import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Shipped | The Armchair Futurist',
  description: 'Verifiable output from my AI agent infrastructure: GitHub pull requests, daily digests, and deployed projects.',
};

export default function ShippedPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-4xl font-bold mb-2">Shipped</h1>
      <p className="text-lg text-gray-500 mb-12">Verifiable output. Every claim backed by a linked artifact.</p>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">Daily AI Digest</h2>
        <p className="mb-4">
          A 2,500-3,000 word AI news digest published every day at 11:00 Lisbon time. Generated by my Hermes agent from HuggingNews, Hacker News, arXiv, and Reddit. Written in my voice. Delivered to Substack.
        </p>
        <a href="/blog" className="text-blue-600 underline">Read the latest digest</a>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">GitHub Activity</h2>
        <p className="mb-4">
          Pull requests, issues, and commits filed by my agent on my public repos. Each one links to the actual code.
        </p>
        <a href="https://github.com/armchairfuturist-code" className="text-blue-600 underline">armchairfuturist-code on GitHub</a>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">Client Projects</h2>
        <ul className="space-y-6">
          <li>
            <strong>mindscape-site</strong> — Next.js 16 site deployed on Cloud Run. Full-stack build with agent-assisted development, testing, and deployment.
          </li>
          <li>
            <strong>rooted-leader-site</strong> — React 19 site deployed on Firebase. Substack integration with automated content fetching.
          </li>
          <li>
            <strong>ArmchairFuturistLanding</strong> — This site. Next.js 16, Firebase Hosting, Cloud Build CI/CD. Blog, case studies, assessment, and now a public agent infrastructure page.
          </li>
        </ul>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">Open Source Tools</h2>
        <ul className="space-y-4">
          <li>
            <strong>Investment-Engine</strong> — Python MCP server for portfolio analysis. CI with pytest and ruff. Docker deployment.
          </li>
          <li>
            <strong>bio-orchestrator</strong> — Streamlit app for health data analysis. Blood work, DNA markers, methylation data.
          </li>
          <li>
            <strong>novel-writer-harness</strong> — Python CLI for AI-assisted fiction writing with structured chapter management.
          </li>
          <li>
            <strong>FALA</strong> — Python CLI for voice synthesis and AI audio generation.
          </li>
        </ul>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-4">Infrastructure</h2>
        <p>
          Full agent infrastructure documentation at <a href="/how-i-work" className="text-blue-600 underline">/how-i-work</a>.
          Operating policies at <a href="https://github.com/armchairfuturist-code/.hermes/blob/main/POLICIES.md" className="text-blue-600 underline">POLICIES.md</a>.
        </p>
      </section>
    </main>
  );
}
